import { Inter } from "next/font/google";
import "./globals.css";
// import { UserContext } from "@/context/User";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <UserContext.Provider> */}
        <body className={inter.className}>{children}</body>
      {/* </UserContext.Provider> */}
    </html>
  );
}
